version: "2"
services:
  web:
    container_name: "users"
    build: ./web
    ports:
     - "5002:5000"
    volumes:
     - ./web:/code
    command: "python3 app.py"
    restart: "on-failure"
    networks: 
     - default
     - backend

  storage:
    image: redis
    ports:
      - "6666:6379"

networks:
  backend:
    external: true