# Generated by Django 2.0.10 on 2019-01-26 02:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='minute_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='minute_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=100),
        ),
    ]
