version: "2"

services:
  db:
    image: mdillon/postgis
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  web:
    container_name: "matches"
    build: ./web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    image: matches
    restart: "on-failure"

    networks:
      - default
      - backend
  
#development containers
  migrate:
    build: ./web
    command: python3 manage.py migrate
    volumes:
      - ./web/:/code
    depends_on:
      - db
    image: matches
    restart: on-failure

  make_migrations:
    build: ./web
    command: python3 manage.py makemigrations
    volumes:
      - ./web/:/code
    depends_on:
      - db
    image: matches
    restart: on-failure

networks:
  backend:
    external: true
